@echo off
echo Starting Chrome in debug mode for Birthday Video...
"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir=C:\temp\chrome-debug-birthday about:blank
