@echo off
start "" "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir=C:\temp\chrome-debug-birthday about:blank
echo Chrome起動完了！ポート9222でデバッグモード実行中...
